#! /bin/sh

source ~/.bash_profile

sxhkd &

if [ `hostname` -eq 'mplamann-desktop' ]; then
	bspc monitor DP-2 -d I II III IV V
	bpsc monitor HDMI-0 -d VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
PATH=~/scripts:${PATH} changebg ~/Pictures/`ls ~/Pictures | shuf -n 1`

bspc config top_padding 15
PATH=~/scripts:${PATH} panel 1>/home/mplamann/log 2>/home/mplamann/log &
