#! /bin/sh

source ~/.bash_profile

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-scale ~/Pictures/vulpix-and-eevee-ceafbfcffcd-542720.jpg

bspc config top_padding 15
PATH=~/scripts:${PATH} panel 1>/home/mplamann/log 2>/home/mplamann/log &
